### ISSUE TITLE
when will you Post this code.

### ISSUE THREAD

**Issue by BruteDoom** [NoNameoN-A/IP-Logger#1]
I'm so curious to Know how its works is it really possible and where its work ios, android, windows. please post project

**Comment by BruteDoom** [comment]
can you look this short video platform for while https://www.mxtakatak.com/ 
i want like bot and viewbot for this application, can you please make something for this please

**Comment by NoNameoN-A** [comment]
is posted, you just read the README.md file

**Comment by NoNameoN-A** [comment]
I can't post the code and i can't post the resoult
